@echo off
echo Инициализация Git репозитория...
git init
echo Добавление файлов...
git add .
echo Создание коммита...
git commit -m "Initial commit"
echo Создание ветки main...
git branch -M main
echo Для завершения введите URL вашего репозитория в формате:
echo https://github.com/username/repository.git
set /p repo_url="URL репозитория: "
echo Добавление удаленного репозитория...
git remote add origin %repo_url%
echo Отправка кода в репозиторий...
git push -u origin main
echo Готово!
pause 